name: ffmpeg_wasm
description: ffmpeg.wasm browser APIs dart port for accessing in Flutter web.
version: 0.0.1
homepage: "https://github.com/redleafsofts/ffmpeg_wasm_flutter"
repository: "https://github.com/redleafsofts/ffmpeg_wasm_flutter"

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  js: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


#flutter:
#  plugin:
#    platforms:
#      web:
#        pluginClass: FFmpeg
#        fileName: src/ffmpeg.dart